###
GET http://localhost:3000/rooms
Content-Type: application/json

###
POST http://localhost:3000/rooms
Content-Type: application/json

{
    "roomId": "R-82089498-95c7-4281-b2bf-59e10a11c159",
    "game": "tictactoe",
    "player": {
        "uuid": "12ae1907-b79f-4e99-82e1-fe7604a9d33a",
        "nickname": "chaps"
    }
}
###
PUT http://localhost:3000/rooms
Content-Type: application/json

{
    "roomId": "R-82089491-95c7-4281-b2bf-57e10a11c160",
    "player": {
        "uuid": "12ae1907-b79f-4e99-82e1-fe7604a5d33a",
        "nickname": "chaps"
    }
}